require 'busted.runner'()
require("rena")

function match(pattern, string, match, lastIndex)
    local result = pattern(string, 1, nil)
    assert.are.equal(result.match, match)
    assert.are.equal(result.lastIndex, lastIndex + 1)
end

function matchAttr(pattern, string, match, lastIndex, attr)
    local result = pattern(string, 1, nil)
    assert.are.equal(result.match, match)
    assert.are.equal(result.lastIndex, lastIndex + 1)
    assert.are.equal(result.attr, attr)
end

function matchpos(pattern, string, startPos, match, lastIndex)
    local result = pattern(string, startPos, nil)
    assert.are.equal(result.match, match)
    assert.are.equal(result.lastIndex, lastIndex + 1)
end

function nomatch(pattern, string)
    local result = pattern(string, 1, nil)
    assert.are.equal(result, nil)
end

function nomatchpos(pattern, string, startPos)
    local result = pattern(string, startPos, nil)
    assert.are.equal(result, nil)
end

function matchattr(pattern, string, match, lastIndex, attrFunction)
    local result = pattern(string, 1, nil)
    assert.are.equal(result.match, match)
    assert.are.equal(result.lastIndex, lastIndex + 1)
    assert.are.equal(attrFunction(result.attr), true)
end

function fntest(match, lastIndex, attr)
    if string.sub(match, lastIndex, lastIndex) == "a" then
        return {
            match = "a",
            lastIndex = lastIndex + 1,
            attr = attr
        }
    else
        return nil
    end
end

local r = Rena()

describe("match", function()
    it("simple match", function()
        match(r.con("string"), "string", "string", 6)
        match(r.con("string"), "strings", "string", 6)
        nomatch(r.con("string"), "strin")
        match(r.con(""), "string", "", 0)
    end)

    it("simple function match", function ()
        match(r.con(fntest), "a", "a", 1)
        nomatch(r.con(fntest), "s")
    end)

    it("chaining con", function ()
        local ptn = r.con("string", "match")
        match(ptn, "stringmatch", "stringmatch", 11)
        match(ptn, "stringmatches", "stringmatch", 11)
        nomatch(ptn, "stringmatc")
        nomatch(ptn, "strinmatch")
    end)

    it("conAction", function ()
        matchAttr(r.con(r.attr(1), r.conAction(r.real(), "+", r.real(), function(a, _2, b, inh)
            return a + b - inh
        end)), "765+346", "765+346", 7, 1110);
        nomatch(r.conAction(r.real(), "+", r.real(), function() end), "765-961")
    end);

    it("real", function ()
        local function assertReal(str, val)
            local matcher = r.real()
            assert.are.equal(matcher(str, 1, false).attr, val)
        end
        assertReal("765", 765)
        assertReal("76.5", 76.5)
        assertReal("0.765", 0.765)
        assertReal(".765", 0.765)
        assertReal("765e2", 76500)
        assertReal("765E2", 76500)
        assertReal("765e+2", 76500)
        assertReal("765e-2", 7.65)
        --assertReal("765e+346", Infinity)
        assertReal("765e-346", 0)
        nomatch(r.real(), "a961")
        assertReal("+765", 765)
        assertReal("+76.5", 76.5)
        assertReal("+0.765", 0.765)
        assertReal("+.765", 0.765)
        assertReal("+765e2", 76500)
        assertReal("+765E2", 76500)
        assertReal("+765e+2", 76500)
        assertReal("+765e-2", 7.65)
        --assertReal("+765e+346", Infinity)
        assertReal("+765e-346", 0)
        nomatch(r.real(), "+a961")
        assertReal("-765", -765)
        assertReal("-76.5", -76.5)
        assertReal("-0.765", -0.765)
        assertReal("-.765", -0.765)
        assertReal("-765e2", -76500)
        assertReal("-765E2", -76500)
        assertReal("-765e+2", -76500)
        assertReal("-765e-2", -7.65)
        --assertReal("-765e+346", -Infinity)
        assertReal("-765e-346", 0)
        nomatch(r.real(), "-a961")
    end)

    it("br", function ()
        match(r.br(), "\n", "\n", 1)
        match(r.br(), "\r", "\r", 1)
        match(r.br(), "\r\n", "\r\n", 2)
        nomatch(r.br(), "a")
    end)

    it("ending", function ()
        match(r.con("765", r.isEnd()), "765", "765", 3)
        nomatch(r.con("765", r.isEnd()), "765961")
        match(r.isEnd(), "", "", 0)
    end)

    it("equalsId", function ()
        local q1 = Rena({ ignore = " " })
        local q2 = Rena({ keys = {"+", "++", "-"} })
        local q3 = Rena({ ignore = " ", keys = {"+", "++", "-"} })
        match(r.equalsId("if"), "if", "if", 2)
        match(r.equalsId("if"), "if ", "if", 2)
        match(r.equalsId("if"), "iff", "if", 2)
        match(q1.equalsId("if"), "if", "if", 2)
        match(q1.equalsId("if"), "if ", "if ", 3)
        nomatch(q1.equalsId("if"), "iff")
        nomatch(q1.equalsId("if"), "if+")
        match(q2.equalsId("if"), "if", "if", 2)
        match(q2.equalsId("if"), "if+", "if", 2)
        match(q2.equalsId("if"), "if++", "if", 2)
        match(q2.equalsId("if"), "if-", "if", 2)
        nomatch(q2.equalsId("if"), "if ")
        nomatch(q2.equalsId("if"), "iff")
        match(q3.equalsId("if"), "if", "if", 2)
        match(q3.equalsId("if"), "if ", "if ", 3)
        match(q3.equalsId("if"), "if+", "if", 2)
        match(q3.equalsId("if"), "if++", "if", 2)
        match(q3.equalsId("if"), "if-", "if", 2)
        nomatch(q3.equalsId("if"), "iff")
    end)

    it("or", function ()
        local ptn = r.choice("string", r.regex("[0-9]+"), fntest)
        match(ptn, "string", "string", 6)
        match(ptn, "765", "765", 3)
        match(ptn, "a", "a", 1)
        nomatch(ptn, "-")
    end)

    it("matching times", function ()
        match(r.times(2, 4, "str"), "strstr", "strstr", 6)
        match(r.times(2, 4, "str"), "strstrstr", "strstrstr", 9)
        match(r.times(2, 4, "str"), "strstrstrstr", "strstrstrstr", 12)
        match(r.times(2, 4, "str"), "strstrstrstrstr", "strstrstrstr", 12)
        nomatch(r.times(2, 4, "str"), "str")
        match(r.times(2, 2, "str"), "strstr", "strstr", 6)
        match(r.times(2, 2, "str"), "strstrstr", "strstr", 6)
        nomatch(r.times(2, 2, "str"), "str")
        match(r.times(0, 1, "str"), "str", "str", 3)
        match(r.times(0, 1, "str"), "", "", 0)
        match(r.times(0, 1, "str"), "strstr", "str", 3)
        match(r.times(2, false, "str"), "strstr", "strstr", 6)
        match(r.times(2, false, "str"), "strstrstrstrstr", "strstrstrstrstr", 15)
        nomatch(r.times(2, false, "str"), "str")
        match(r.times(0, 0, "str"), "strstr", "", 0)
    end)

    it("atLeast", function ()
        match(r.atLeast(2, "str"), "strstr", "strstr", 6)
        match(r.atLeast(2, "str"), "strstrstrstrstr", "strstrstrstrstr", 15)
        nomatch(r.atLeast(2, "str"), "str")
    end)

    it("atMost", function ()
        match(r.atMost(4, "str"), "", "", 0)
        match(r.atMost(4, "str"), "str", "str", 3)
        match(r.atMost(4, "str"), "strstr", "strstr", 6)
        match(r.atMost(4, "str"), "strstrstr", "strstrstr", 9)
        match(r.atMost(4, "str"), "strstrstrstr", "strstrstrstr", 12)
        match(r.atMost(4, "str"), "strstrstrstrstr", "strstrstrstr", 12)
    end)

    it("maybe", function ()
        match(r.maybe("string"), "string", "string", 6)
        match(r.maybe("string"), "strings", "string", 6)
        match(r.maybe("string"), "strin", "", 0)
        match(r.maybe("string"), "stringstring", "string", 6)
    end)

    it("oneOrMore", function ()
        match(r.oneOrMore("str"), "str", "str", 3)
        match(r.oneOrMore("str"), "strstrstrstrstr", "strstrstrstrstr", 15)
        nomatch(r.oneOrMore("str"), "")
    end)

    it("zeroOrMore", function ()
        match(r.zeroOrMore("str"), "", "", 0)
        match(r.zeroOrMore("str"), "str", "str", 3)
        match(r.zeroOrMore("str"), "strstrstrstrstr", "strstrstrstrstr", 15)
    end)

    it("delimit", function ()
        match(r.delimit(r.regex("[0-9]+"), "+"), "7", "7", 1)
        match(r.delimit(r.regex("[0-9]+"), "+"), "7+65", "7+65", 4)
        match(r.delimit(r.regex("[0-9]+"), "+"), "7+", "7", 1)
        nomatch(r.delimit(r.regex("[0-9]+"), "+"), "")
        nomatch(r.delimit(r.regex("[0-9]+"), "+"), "a+7")
        nomatch(r.delimit(r.regex("[0-9]+"), "+"), "+961")
    end)

    it("triesTimes", function ()
        match(r.triesTimes(2, 5, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesTimes(2, 5, "ab", "abab"), "ababababababab", "ababababababab", 14)
        match(r.triesTimes(2, 5, "ab", "abab"), "abababababababab", "ababababababab", 14)
        nomatch(r.triesTimes(2, 5, "ab", "abab"), "ababab")
        nomatch(r.triesTimes(2, 5, "ab", "abab"), "abababc")
        match(r.triesTimes(2, 2, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesTimes(2, 2, "ab", "abab"), "ababababab", "abababab", 8)
        nomatch(r.triesTimes(2, 2, "ab", "abab"), "ababab")
        match(r.triesTimes(0, 2, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesTimes(0, 2, "ab", "abab"), "abab", "abab", 4)
        match(r.triesTimes(0, 2, "ab", "abab"), "ababababab", "abababab", 8)
        match(r.triesTimes(2, nil, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesTimes(2, nil, "ab", "abab"), "abababababababab", "abababababababab", 16)
        nomatch(r.triesTimes(2, nil, "ab", "abab"), "ababab")
        nomatch(r.triesTimes(2, nil, "ab", "abab"), "abababc")
        assert.are.equal(r.triesTimes(0, nil, "ab", "abab", function(match, syn, inh) return inh + 2; end)("abababab", 1, 0).attr, 4)
    end)

    it("triesAtLeast", function ()
        match(r.triesAtLeast(2, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesAtLeast(2, "ab", "abab"), "abababababababab", "abababababababab", 16)
        nomatch(r.triesAtLeast(2, "ab", "abab"), "ababab")
        nomatch(r.triesAtLeast(2, "ab", "abab"), "abababc")
    end)

    it("triesAtMost", function ()
        match(r.triesAtMost(2, "ab", "abab"), "abababab", "abababab", 8)
        match(r.triesAtMost(2, "ab", "abab"), "abab", "abab", 4)
        match(r.triesAtMost(2, "ab", "abab"), "ababababab", "abababab", 8)
    end)

    it("triesZeroOrMore", function ()
        match(r.triesZeroOrMore("ab", "abab"), "abab", "abab", 4)
        match(r.triesZeroOrMore("ab", "abab"), "abababababababab", "abababababababab", 16)
        nomatch(r.triesZeroOrMore("ab", "abab"), "ab")
        nomatch(r.triesZeroOrMore("ab", "abab"), "abc")
    end)

    it("triesOneOrMore", function ()
        match(r.triesOneOrMore("ab", "abab"), "ababab", "ababab", 6)
        match(r.triesOneOrMore("ab", "abab"), "abababababababab", "abababababababab", 16)
        nomatch(r.triesOneOrMore("ab", "abab"), "abab")
        nomatch(r.triesOneOrMore("ab", "abab"), "ababc")
    end)

    it("triesMaybe", function ()
        match(r.triesMaybe("string", "!"), "string!", "string!", 7)
        match(r.triesMaybe("string", "!"), "!", "!", 1)
        nomatch(r.triesMaybe("string", "!"), "strin")
    end)

    it("triesTimesNonGreedy", function ()
        match(r.triesTimesNonGreedy(2, 8, r.regex("."), ","), "a,a,a,aa", "a,a,", 4)
        nomatch(r.triesTimesNonGreedy(2, 8, r.regex("."), ","), "a,")
        match(r.triesTimesNonGreedy(2, 8, r.regex("."), ","), "aaaaaaaa,", "aaaaaaaa,", 9)
        nomatch(r.triesTimesNonGreedy(2, 8, r.regex("."), ","), "aaaaaaaaa,")
        nomatch(r.triesTimesNonGreedy(2, 8, r.regex("."), ","), "aaaaaaa")
        match(r.triesTimesNonGreedy(2, false, r.regex("."), ","), "a,aaa,aaa", "a,aaa,", 6)
        nomatch(r.triesTimesNonGreedy(2, false, r.regex("."), ","), "a,")
        nomatch(r.triesTimesNonGreedy(2, false, r.regex("."), ","), "aaaaaa")
        match(r.triesTimesNonGreedy(0, 8, r.regex("."), ","), "aa,aa,aa", "aa,", 3)
        match(r.triesTimesNonGreedy(0, 8, r.regex("."), ","), "aaaaaaaa,", "aaaaaaaa,", 9)
        nomatch(r.triesTimesNonGreedy(0, 8, r.regex("."), ","), "aaaaaaaaa,")
        nomatch(r.triesTimesNonGreedy(0, 8, r.regex("."), ","), "aaaaaaa")
        assert.are.equal(r.triesTimesNonGreedy(2, false, r.regex("."), ",", function(match, syn, inh) return inh + 1 end)("aaa,a,a", 1, 0).attr, 3)
    end)

    it("triesAtLeastNonGreedy", function ()
        match(r.triesAtLeastNonGreedy(2, r.regex("."), ","), "a,aaa,aaa", "a,aaa,", 6)
        nomatch(r.triesAtLeastNonGreedy(2, r.regex("."), ","), "a,")
        nomatch(r.triesAtLeastNonGreedy(2, r.regex("."), ","), "aaaaaa")
    end)

    it("triesAtMostNonGreedy", function ()
        match(r.triesAtMostNonGreedy(8, r.regex("."), ","), "aa,aa,aa", "aa,", 3)
        match(r.triesAtMostNonGreedy(8, r.regex("."), ","), "aaaaaaaa,", "aaaaaaaa,", 9)
        nomatch(r.triesAtMostNonGreedy(8, r.regex("."), ","), "aaaaaaaaa,")
        nomatch(r.triesAtMostNonGreedy(8, r.regex("."), ","), "aaaaaaa")
    end)

    it("triesZeroOrMoreNonGreedy", function ()
        match(r.triesZeroOrMoreNonGreedy(r.regex("."), ","), "a,aaa,aaa", "a,", 2)
        nomatch(r.triesZeroOrMoreNonGreedy(r.regex("."), ","), "aaaaaa")
    end)

    it("triesOneOrMoreNonGreedy", function ()
        match(r.triesOneOrMoreNonGreedy(r.regex("."), ","), ",a,aaa,aaa", ",a,", 3)
        nomatch(r.triesOneOrMoreNonGreedy(r.regex("."), ","), ",aaaaaa")
    end)

    it("triesMaybeNonGreedy", function ()
        match(r.triesMaybeNonGreedy("string", "!"), "string!", "string!", 7)
        match(r.triesMaybeNonGreedy("string", "!"), "!", "!", 1)
        nomatch(r.triesMaybeNonGreedy("string", "!"), "strin")
    end)

    it("lookahead", function ()
        match(r.con(r.lookahead(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765pro", "765", 3)
        match(r.con(r.regex("[0-9]+"), r.lookahead("pro")), "765pro", "765", 3)
        nomatch(r.con(r.lookahead(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765studio")
        nomatch(r.con(r.regex("[0-9]+"), r.lookahead("pro")), "765studio")
        nomatch(r.con(r.regex("[0-9]+"), r.lookahead("pro")), "765")
        match(r.con(r.lookahead(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765pro", "765", 3)
        match(r.con(r.regex("[0-9]+"), r.lookahead("pro")), "765pro", "765", 3)
        nomatch(r.con(r.regex("[0-9]+"), r.lookahead("pro")), "765studio")
    end)

    it("lookaheadNot", function ()
        match(r.con(r.lookaheadNot(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765studio", "765", 3)
        match(r.con(r.regex("[0-9]+"), r.lookaheadNot("pro")), "765studio", "765", 3)
        match(r.con(r.regex("[0-9]+"), r.lookaheadNot("pro")), "765", "765", 3)
        nomatch(r.con(r.lookaheadNot(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765pro")
        nomatch(r.con(r.regex("[0-9]+"), r.lookaheadNot("pro")), "765pro")
        match(r.con(r.lookaheadNot(r.regex("[0-9]+pro")), r.regex("[0-9]+")), "765studio", "765", 3)
    end)

    it("key", function ()
        local q = Rena({ keys = {"*", "+", "++"} })
        match(q.key("+"), "+", "+", 1)
        match(q.key("++"), "++", "++", 2)
        match(q.key("*"), "*", "*", 1)
    end)

    it("notKey", function ()
        local q = Rena({ keys = {"*", "+", "++"} })
        match(q.notKey(), "/", "", 0)
        nomatch(q.notKey(), "+")
        nomatch(q.notKey(), "++")
        nomatch(q.notKey(), "*")
    end)

    it("skip space", function ()
        local r = Rena({ ignore = r.regex(" +") })
        match(r.con("765", "pro"), "765pro", "765pro", 6)
        match(r.con("765", "pro"), "765  pro", "765  pro", 8)
        nomatch(r.con("765", "pro"), "76 5pro")
    end)

    it("letrec", function ()
        local ptn1
        local function assertParse(str)
            return ptn1(str, 1, 0)
        end

        ptn1 = r.letrec(
            function(t, f, e)
                return r.con(f, r.zeroOrMore(r.choice(
                    r.action(r.con("+", f), function(x, a, b) return b + a end),
                    r.action(r.con("-", f), function(x, a, b) return b - a end))))
            end,
            function(t, f, e)
                return r.con(e, r.zeroOrMore(r.choice(
                    r.action(r.con("*", e), function(x, a, b) return b * a end),
                    r.action(r.con("/", e), function(x, a, b) return b / a end))))
            end,
            function(t, f, e)
                return r.choice(r.real(), r.con("(", t, ")"))
            end)
        assert.are.equal(assertParse("1+2*3").attr, 7)
        assert.are.equal(assertParse("(1+2)*3").attr, 9)
        assert.are.equal(assertParse("4-6/2").attr, 1)
        assert.are.equal(assertParse("1+2+3*3").attr, 12)
    end)

    it("range", function()
        match(r.range(0, 0xffff), "a", "a", 1)
        match(r.range(0, 0xffff), "カ", "カ", 3)
    end)
end)

local function matchre(ptn, aString, matched, length)
    match(r.regex(ptn), aString, matched, length)
end

local function nomatchre(ptn, aString, matched, length)
    nomatch(r.regex(ptn), aString)
end

describe("regex", function()
    it("simple elements", function()
        matchre("a", "a", "a", 1)
        nomatchre("a", "b")
    end)

    it("espace sequence (1 character)", function()
        matchre("\\n", "\n", "\n", 1)
        matchre("\\r", "\r", "\r", 1)
        matchre("\\t", "\t", "\t", 1)
        matchre("\\\\", "\\", "\\", 1)
        matchre("\\.", ".", ".", 1)
        nomatchre("\\.", "1")
    end)

    it("unicode", function()
        matchre("\\u0031", "1", "1", 1)
        matchre("\\u30a2", "ア", "ア", 3)
    end)

    it("defined character set", function()
        matchre("\\d", "0", "0", 1)
        matchre("\\d", "9", "9", 1)
        nomatchre("\\d", "/")
        nomatchre("\\d", ":")
        matchre("\\D", "/", "/", 1)
        matchre("\\D", ":", ":", 1)
        nomatchre("\\D", "0")
        nomatchre("\\D", "9")
    end)

    it("any character without newline", function()
        matchre(".", "a", "a", 1)
        nomatchre(".", "\r")
        nomatchre(".", "\n")
    end)

    it("concatate", function()
        matchre("ab", "ab", "ab", 2)
        nomatchre("ab", "ac")
        nomatchre("ab", "cb")
    end)

    it("alternation", function()
        matchre("a|b", "a", "a", 1)
        matchre("a|b", "b", "b", 1)
        nomatchre("a|b", "c")
        matchre("8765|876", "8765", "8765", 4)
        matchre("876|8765", "8765", "876", 3)
    end)

    it("repeat zero or more", function()
        matchre("a*", "aaa", "aaa", 3)
        matchre("a*", "", "", 0)
        matchre(".*-", "aa-aa-aa", "aa-aa-", 6)
    end)

    it("repeat one or more", function()
        matchre("a+", "aaa", "aaa", 3)
        matchre("a+", "a", "a", 1)
        nomatchre("a+", "")
        matchre(".+-", "aa-aa-aa", "aa-aa-", 6)
    end)

    it("optional", function()
        matchre("a?", "aaa", "a", 1)
        matchre("a?", "", "", 0)
    end)

    it("repeat from n to m times", function()
        matchre("a{3,5}", "aaa", "aaa", 3)
        matchre("a{3,5}", "aaaaa", "aaaaa", 5)
        matchre("a{3,5}", "aaaaaa", "aaaaa", 5)
        nomatchre("a{3,5}", "aa")
        matchre(".{2,5}-", "aa-aa-", "aa-aa-", 6)
    end)

    it("repeat at least n times", function()
        matchre("a{3,}", "aaa", "aaa", 3)
        matchre("a{3,}", "aaaaa", "aaaaa", 5)
        nomatchre("a{3,}", "aa")
        matchre(".{2,}-", "aa-aa-", "aa-aa-", 6)
    end)

    it("repeat n times", function()
        matchre("a{3}", "aaa", "aaa", 3)
        matchre("a{3}", "aaaa", "aaa", 3)
        nomatchre("a{3}", "aa")
    end)

    it("repeat zero or more non greedy", function()
        matchre("a*?", "", "", 0)
        matchre("a*?", "", "", 0)
        matchre(".*?<br>", "aa<br>aa<br>aa", "aa<br>", 6)
    end)

    it("repeat one or more non greedy", function()
        matchre("a+?", "aaa", "a", 1)
        matchre("a+?", "a", "a", 1)
        nomatchre("a+?", "")
        matchre(".+?<br>", "aa<br>aa<br>aa", "aa<br>", 6)
    end)

    it("optional non greedy", function()
        matchre("a??", "aaa", "", 0)
        matchre("a??", "", "", 0)
    end)

    it("repeat from n to m times non greedy", function()
        matchre("a{3,5}?", "aaa", "aaa", 3)
        matchre("a{3,5}?", "aaaaa", "aaa", 3)
        matchre("a{3,5}?", "aaaaaa", "aaa", 3)
        nomatchre("a{3,5}?", "aa")
        matchre(".{2,10}?<br>", "aa<br>aa<br>", "aa<br>", 6)
    end)

    it("repeat at least n times non greedy", function()
        matchre("a{3,}?", "aaa", "aaa", 3)
        matchre("a{3,}?", "aaaaa", "aaa", 3)
        nomatchre("a{3,}?", "aa")
        matchre(".{2,}?<br>", "aa<br>aa<br>", "aa<br>", 6)
    end)

    it("repeat n times non greedy", function()
        matchre("a{3}?", "aaa", "aaa", 3)
        matchre("a{3}?", "aaaa", "aaa", 3)
        nomatchre("a{3}?", "aa")
    end)

    it("repeat zero or more without backtrack", function()
        matchre("a*+", "aaa", "aaa", 3)
        matchre("a*+", "", "", 0)
        nomatchre(".*+-", "aa-aa-aa")
    end)

    it("repeat one or more without backtrack", function()
        matchre("a++", "aaa", "aaa", 3)
        matchre("a++", "a", "a", 1)
        nomatchre("a++", "")
        nomatchre(".++-", "aa-aa-aa")
    end)

    it("optional", function()
        matchre("a?+", "aaa", "a", 1)
        matchre("a?+", "", "", 0)
    end)

    it("repeat from n to m times without backtrack", function()
        matchre("a{3,5}+", "aaa", "aaa", 3)
        matchre("a{3,5}+", "aaaaa", "aaaaa", 5)
        matchre("a{3,5}+", "aaaaaa", "aaaaa", 5)
        nomatchre("a{3,5}+", "aa")
        nomatchre(".{2,10}+-", "aa-aa-")
    end)

    it("repeat at least n times without backtrack", function()
        matchre("a{3,}+", "aaa", "aaa", 3)
        matchre("a{3,}+", "aaaaa", "aaaaa", 5)
        nomatchre("a{3,}+", "aa")
        nomatchre(".{2,}+-", "aa-aa-")
    end)

    it("repeat n times without backtrack", function()
        matchre("a{3}+", "aaa", "aaa", 3)
        matchre("a{3}+", "aaaa", "aaa", 3)
        nomatchre("a{3}+", "aa")
    end)

    it("lookahead", function()
        matchre("7(?=65)", "765", "7", 1)
        nomatchre("7(?=65)", "766")
    end)

    it("lookahead negative", function()
        matchre("9(?!61)", "901", "9", 1)
        nomatchre("9(?!61)", "961")
    end)

    it("grouping", function()
        local function checkNil(attr)
            return attr[1] == nil
        end
        matchattr(r.regex("(?:ab)+"), "ababab", "ababab", 6, checkNil)
        matchre("(?:ab)+", "abbbbab", "ab", 2)
        matchre("(?:ab)*abab", "abab", "abab", 4)
        --matchre("(?:a+)a", "aaaa", "aaaa", 4)
    end)

    it("capture", function()
        local function checkCapture(attr)
            return attr[1] == "ab" and attr[2] == "cd" and #attr == 2
        end
        matchattr(r.regex("(..)(..)e"), "abcde", "abcde", 5, checkCapture)
        matchre("(ab)+", "abbbbab", "ab", 2)
    end)

    it("refer", function()
        matchre("(..)(..)\\2\\1", "abcdcdab", "abcdcdab", 8)
        nomatchre("(..)(..)\\2\\1", "abcdabcd")
        --matchre("(.+)\\1", "abcdabcd", "abcdabcd", 8)
        --nomatchre("(.+)\\1", "abcdabcd")
    end)

    it("starting anchor", function()
        matchre("^abc", "abc", "abc", 3)
        nomatchpos(r.regex("^abc"), "bc", 2)
    end)

    it("ending anchor", function()
        matchre("abc$", "abc", "abc", 3)
        nomatchre("abc$", "abcd")
    end)

    it("character set 1", function()
        matchre("[bcf]", "b", "b", 1)
        matchre("[bcf]", "c", "c", 1)
        matchre("[bcf]", "f", "f", 1)
        nomatchre("[bcf]", "a")
        nomatchre("[bcf]", "d")
        nomatchre("[bcf]", "e")
        nomatchre("[bcf]", "g")
    end)

    it("character set - range", function()
        matchre("[c-x]", "c", "c", 1)
        matchre("[c-x]", "x", "x", 1)
        nomatchre("[c-x]", "b")
        nomatchre("[c-x]", "y")
        matchre("[c-eg]", "c", "c", 1)
        matchre("[c-eg]", "g", "g", 1)
        nomatchre("[c-eg]", "f")
    end)

    it("complementary character set 1", function()
        matchre("[^bcf]", "a", "a", 1)
        matchre("[^bcf]", "d", "d", 1)
        matchre("[^bcf]", "e", "e", 1)
        matchre("[^bcf]", "g", "g", 1)
        nomatchre("[^bcf]", "b")
        nomatchre("[^bcf]", "c")
        nomatchre("[^bcf]", "f")
    end)

    it("complementary character set - range", function()
        matchre("[^c-x]", "b", "b", 1)
        matchre("[^c-x]", "y", "y", 1)
        nomatchre("[^c-x]", "c")
        nomatchre("[^c-x]", "x")
    end)

    it("character set - escape", function()
        matchre("[\\n]", "\n", "\n", 1)
        nomatchre("[\\n]", "\r")
        matchre("[c\\-x]", "c", "c", 1)
        matchre("[c\\-x]", "x", "x", 1)
        matchre("[c\\-x]", "-", "-", 1)
        nomatchre("[c\\-x]", "b")
        nomatchre("[c\\-x]", "d")
        nomatchre("[c\\-x]", "w")
        nomatchre("[c\\-x]", "y")
        matchre("[a^]", "^", "^", 1)
        matchre("[\\--x]", "-", "-", 1)
        matchre("[\\--x]", "x", "x", 1)
        nomatchre("[\\--x]", "y")
    end)

    it("character set - unicode", function()
        matchre("[カ-コ]", "カ", "カ", 3)
        matchre("[カ-コ]", "コ", "コ", 3)
        nomatchre("カ-コ]", "サ")
    end)
end)

